# Elegoo PETG PRO — dal profilo ufficiale "Elegoo PETG PRO @ECC" (OrcaSlicer)
filament_type = PETG
first_layer_temperature = 240
temperature = 240
first_layer_bed_temperature = 70
bed_temperature = 70
fan_always_on = 1
cooling = 1
min_fan_speed = 10
max_fan_speed = 40
bridge_fan_speed = 80
fan_below_layer_time = 30
filament_max_volumetric_speed = 8
filament_cost = 24
filament_density = 1.27
filament_colour = #2D2D2D
start_filament_gcode = ;--- prime line PETG (vms 8: F3200/1200) ---\nG1 F3200\nG1 X0 E10.156 ;Draw the first line\nG1 Y98.8 E7.934\nG1 X0.9 Y100 E0.1\nG1 Y-0.3 E7.934\nG1 X78 E6.284\nG1 F1200\nG1 X98 E2\nG1 F3200\nG1 X118 E2\nG1 F1200\nG1 X138 E2\nG1 F3200\nG1 X158 E2\nG1 F1200\nG1 X178 E2\n;End PA test.\nG3 I-1 J0 Z0.6 F1200.0 ;Move to side a little\nG1 F20000\nG92 E0 ;Reset Extruder\nSET_PRINT_STATS_INFO TOTAL_LAYER=[total_layer_count] CURRENT_LAYER=0\n
