# Elegoo PLA — dal profilo ufficiale "Elegoo PLA @ECC" (OrcaSlicer)
filament_type = PLA
first_layer_temperature = 210
temperature = 210
first_layer_bed_temperature = 60
bed_temperature = 60
fan_always_on = 1
cooling = 1
min_fan_speed = 100
max_fan_speed = 100
bridge_fan_speed = 100
fan_below_layer_time = 60
filament_max_volumetric_speed = 21
filament_cost = 20
filament_density = 1.24
filament_colour = #FF6A00
start_filament_gcode = ;--- PLA: fan anti-jam (bed > 50, da profilo ufficiale) ---\nM106 P3 S255\n;--- prime line (vms 21: F6000/1680/8400) ---\nG1 F6000\nG1 X0 E10.156 ;Draw the first line\nG1 Y98.8 E7.934\nG1 X0.9 Y100 E0.1\nG1 Y-0.3 E7.934\nG1 X78 E6.284\nG1 F1680\nG1 X98 E2\nG1 F8400\nG1 X118 E2\nG1 F1680\nG1 X138 E2\nG1 F8400\nG1 X158 E2\nG1 F1680\nG1 X178 E2\n;End PA test.\nG3 I-1 J0 Z0.6 F1200.0 ;Move to side a little\nG1 F20000\nG92 E0 ;Reset Extruder\nSET_PRINT_STATS_INFO TOTAL_LAYER=[total_layer_count] CURRENT_LAYER=0\n
