# Elegoo PETG PRO — dal profilo ufficiale "Elegoo PETG PRO @ECC" (OrcaSlicer)
filament_type = PETG
first_layer_temperature = 240
temperature = 240
first_layer_bed_temperature = 70
bed_temperature = 70
fan_always_on = 1
cooling = 1
min_fan_speed = 10
max_fan_speed = 40
bridge_fan_speed = 80
fan_below_layer_time = 30
filament_max_volumetric_speed = 8
filament_cost = 24
filament_density = 1.27
filament_colour = #2D2D2D
